### ISSUE TITLE
BidirHorizontalLayoutGroup-Editor.asmdef prevents game from being compiled

### ISSUE THREAD

**Issue by JesseTG** [hk1ll3r/BidirectionalHorizontalLayoutGroup#1]
Right now, `BidirHorizontalLayoutGroup-Editor.asmdef` prevents a game from being compiled into standalone builds; it uses `UnityEditor` APIs, but the assembly is not marked as being editor-only.

**Comment by hk1ll3r** [comment]
Noted, will fix it in a few days. Thanks.

**Comment by JesseTG** [comment]
No problem.

**Comment by hk1ll3r** [comment]
Updated the assembly definition to be specific to editor platform. Build for PC tested.
