### ISSUE TITLE
Consider submission to OpenUPM

### ISSUE THREAD

**Issue by JesseTG** [hk1ll3r/BidirectionalHorizontalLayoutGroup#2]
[OpenUPM](https://openupm.com/) is a package registry for free and open source Unity packages, much like this one. Submitting this library there might get you some new users.

**Comment by JesseTG** [comment]
Actually, wait, looking at the process, it looks like packages don't have to be submitted by the original author. [So I went ahead and did it.](https://github.com/openupm/openupm/pull/62)

**Comment by favoyang** [comment]
@hk1ll3r,

I'm the creator of OpenUPM. Your package has been submitted to the platform (thanks for @JesseTG) . Looks great so far. You still need create a GitHub Release (git tag) `1.0.1`, so our build pipelines will publish package based on it. (learn more at https://openupm.com/docs/#automatic-build-pipelines)
