### ISSUE TITLE
Licensing options?

### ISSUE THREAD

**Issue by JesseTG** [hk1ll3r/BidirectionalHorizontalLayoutGroup#3]
I see that `BidirectionalHorizontalLayoutGroup` is released under the GPL. I'm working on a commercial game for which this library would be useful, but I can't use GPL-licensed libraries.

Do you plan on making this tool available under a commercial or permissive license?

**Comment by hk1ll3r** [comment]
I meant this to be free for commercial use. I'll change the LICENSE to MIT.
Use it. A positive review on assetstore is apprecited :)

**Comment by JesseTG** [comment]
Thank you. I will give a review once I finish the part of my project that uses this.

**Comment by hk1ll3r** [comment]
switched to MIT license.
